apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# inherit the canonical manifests
resources:
  - ../../base

# tweak only what differs in dev
images:
  - name: ghcr.io/gmarmstrong/echo-service # match base YAML
    newName: ghcr.io/gmarmstrong/echo-service # unchanged repo
    newTag: dev # tag to build locally

patches:
  - target:
      kind: Deployment
      name: echo-service
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: echo-service
      spec:
        template:
          spec:
            containers:
              - name: app
                imagePullPolicy: IfNotPresent
